# -*- coding: utf-8 -*-
"""GymPredict_projeto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsKW2C2YINqrnWpByrCrpJsBvW3kOWeI

MACHINE LEARNING // classificacao

- ***academia***

-objetivo : previsao de cancelamento de alunos

-dados necessários : idade,tipo de plano, tempo de matricula, historico de pagamentos, frequencia de treinos

-resultado esperado : prever quais alunos têm maior chance de cancelar o plano.

# **GymPredict: Previsão de Cancelamento de Alunos**
- peguei dados de varias academias e montei meu proprio data set com isso analisei os possiveis clientes que podem cancelar suas matriculas(churn) permitindo que a academia tome acoes preventivas para reter clientes
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/gympredict_dataset_100_linhas.csv")
#df.head(10)
#df.info()
#df.describe()
df

# taxa de cancelamento
df["cancelou"].value_counts()

#cancelamento por plano
# pd.crosstab == usada para criar uma tabela de frequencia entre duas ou mais variaveis
pd.crosstab(df["cancelou"], df["plano"])

# frequencia x cancelamento
# vimos que: quem menos frequenta mais cancela o plano
df.groupby("cancelou")["frequencia_semanal"].mean()

# satisfacao x cancelamento
# menos satisfacao mais cancelamentos
df.groupby("cancelou")["avaliacao_satisfacao"].mean()

#pagamento atrasado x cancelamento
#clientes inadimplentes cancelam mais matriculas
pd.crosstab(df["pagamento_atrasado"],df["cancelou"])

"""- Treinar modelo de classificacao // prevendo um novo aluno no dataset"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

x = df[['idade','tempo_matricula_meses',	'frequencia_semanal','faltas_mes','pagamento_atrasado',	'valor_mensalidade',	'avaliacao_satisfacao']]
y = df['cancelou']

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

modelo = LogisticRegression(max_iter=1000)
modelo.fit(x_train,y_train)

novo_aluno = [22,4,5,1,0,199,6]
previsao = modelo.predict([novo_aluno])
print(previsao)

"""(***Random Forest***) prever se o aluno vai cancelar ou nao"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

df = pd.read_csv("/content/gympredict_dataset_100_linhas.csv")

# tranformar a coluno plano em numeros
df = pd.get_dummies(df, columns=['plano'],drop_first=True)

x = df.drop(['cancelou','id_aluno'],axis=1)
y = df['cancelou']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(x_train,y_train)

y_pred = modelo.predict(x_test)

print("Acuracia:", accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

"""- CLASSE 1

Precision 60%: quando o modelo previu que um cliente iria cancelar, acertou 60% das vezes.

Recall 75%: conseguiu identificar 75% dos clientes que realmente cancelaram.

F1-Score 67%: representa o equilíbrio entre precision e recall para a classe de cancelamento.

Support 8: existiam 8 clientes que cancelaram no conjunto de teste.



- CLASSE 0

Precision 80%: quando o modelo previu "Não Cancelou", acertou 80% das vezes.

Recall 67%: conseguiu identificar 67% dos clientes que realmente não cancelaram.

F1-Score 73%: representa o equilíbrio entre precision e recall.

Support 12: existiam 12 clientes dessa classe no conjunto de teste.


"""

import pandas as pd

importancias = pd.DataFrame({
    "Variavel": x.columns,
    "Importancia": modelo.feature_importances_
})

print(
    importancias.sort_values(
        by="Importancia",
        ascending=False
    )
)

# aqui vemos a importancia das variaveis para o projeto
# 1 - frequencia semanal mais importante = clientes que frequentam pouco tem maior chance de cancelar
# 2 - faltas no mes = quanto mais falta mais cancelamento
# 3 - pagamento atrasado = quanto mais atrasa o cancelamento mais cancelam

# probabilidade de cancelamento (classe 1)
# predict_proba = mostra o nivel de confianca do modelo
probabilidade = modelo.predict_proba(x)[:,1]

# criar tabela power bi
resultado = df.copy()
resultado["probabilidade_cancelamento"] = probabilidade
resultado.head()

# criando classificacao de risco
# estamos criando uma nova coluna "risco" com base na probabilidade_cancelamento
#Se a probabilidade for maior ou igual a 0,7 (70%) → "Alto"
#Se a probabilidade for entre 0,4 e 0,69 → "Médio"
#Se a probabilidade for menor que 0,4 → "Baixo"

resultado["risco"] = resultado["probabilidade_cancelamento"].apply(
    lambda x: "Alto"
    if x >= 0.7
    else "Medio"
    if x >= 0.4
    else "baixo"
)

resultado.to_csv(
    "previsao_cancelamento_powerbi.csv",
    index=False
)